fix argument check

diff --git a/dvbr b/dvbr
--- a/dvbr
+++ b/dvbr
@@ -63,16 +63,16 @@ check_storage() {
 }
 
 # check argument count
-check_argument_count() {
-    if [ "$#" -lt 2 ]; then
-        echo "Error: Invalid number of arguments"
-        usage
-        exit 1
-    fi
-}
-
-check_mode() {
-    if [ "$mode" != "backup" ] && [ "$mode" != "restore" ]; then
+check_arguments() {
+    if [ "$mode" == "update" ]; then
+        return
+    elif [ "$mode" == "backup" ] || [ "$mode" == "restore" ]; then
+        if [ -z "$volume" ]; then
+            echo "Error: Volume name must be provided for backup or restore mode"
+            usage
+            exit 1
+        fi
+    else
         echo "Error: Invalid mode"
         usage
         exit 1
@@ -93,8 +93,7 @@ check_volume() {
 
 startup_checks() {
     check_storage
-    check_argument_count
-    check_mode
+    check_arguments
     check_volume
 }
 
@@ -110,10 +109,11 @@ startup_checks
 # If mode is 'backup':
 if [ "$mode" == "backup" ]; then
     # check directories:
-    mkdir -p /mnt/dvbr/$volume
+    finalpath=$storage_path/$volume
+    mkdir -p $finalpath
     echo "Starting backup for Volume $volume..."
     # backup volume
-    docker run --rm --mount source=$volume,target=/mnt/backmeup -v /mnt/dvbr/$volume/:/mnt/backups busybox sh -c "cd /mnt/backmeup && tar czf /mnt/backups/backup-$(date +'%Y%d%m-%H%M%S').tar.gz ."
+    docker run --rm --mount source=$volume,target=/mnt/backmeup -v $finalpath/:/mnt/backups busybox sh -c "cd /mnt/backmeup && tar czf /mnt/backups/backup-$(date +'%Y%d%m-%H%M%S').tar.gz ."
     echo "Backup done."
 fi
 
