check for docker

diff --git a/dvbr b/dvbr
--- a/dvbr
+++ b/dvbr
@@ -37,6 +37,13 @@ usage() {
     echo "  $0 update -> Updates the script to the latest version."
 }
 
+check_docker() {
+    if ! command -v docker &> /dev/null; then
+        echo "Error: Docker is not installed."
+        exit 1
+    fi
+}
+
 # Function to check for updates and update the script
 check_for_updates() {
     local url="https://raw.githubusercontent.com/fsteltenkamp/dvbr/main/dvbr"
@@ -99,6 +106,7 @@ check_volume() {
 }
 
 startup_checks() {
+    check_docker
     check_storage
     check_arguments
     check_volume
